### ISSUE TITLE
BSV20 sends from Panda reverse the locking script and inscription script

### ISSUE THREAD

**Issue by jdh7190** [yours-org/yours-wallet#147]
Example txid:

https://whatsonchain.com/tx/92aa3501c152ba34d399140d55f05fe7df65cdafe0f5ee2e9a8264566a4f8e5c

Notice the inscription script is leading, and the P2PKH script is after the inscription script

This is making so existing processes of trying to unlock these scripts fail. It is uncertain if these outputs are spendable or not.

**Comment by jdh7190** [comment]
Update - these are indeed spendable. But i still think the order should be corrected and consistent with all other services/wallets/marketplaces

**Comment by danwag06** [comment]
@shruggr I'm good with whatever you think.

**Comment by shruggr** [comment]
The problem is that there is no consistent. sCrypt HAS to place the inscription first. It is not possible for it to come after in stateful contracts, but all, from the beginning have had the inscription last.

It is a trivial change to make the default send from Panda be the same as the original default and put the inscription after the locking script, but this does need to be fixed by other wallets to support it either way. Otherwise sCrypt-minted tokens will not be compatible with their wallets.

@jdh7190 who do I need to talk with about this, and where are these conversations happening so I can take part?
